"""
AI tool detection from commit messages and trailers.

This module is imported and used by both:
- clone-worker (during live extraction)
- corpus migration (during bulk migration)

The detection logic lives in ONE place to prevent drift between
the two code paths. Do not reimplement these patterns in SQL or
elsewhere — any update to tool signatures should be made here.

This module operates on individual commit message text and returns
detected tools. It is designed to be called per-commit during both
live extraction and bulk migration.
"""

import re
from typing import Set, Optional, List, Dict, Any
from dataclasses import dataclass
from datetime import date


@dataclass
class DetectionResult:
    """
    Result of AI tool detection for a single commit.

    Attributes:
        tools: Set of detected tool names (e.g., {'claude-code', 'cursor'})
        is_ai_tagged: True if any AI tool signature was detected
        raw_message: The original commit message (for debugging)
    """
    tools: Set[str]
    is_ai_tagged: bool
    raw_message: str

    def __post_init__(self):
        """Ensure is_ai_tagged reflects the tools set."""
        if self.is_ai_tagged and not self.tools:
            raise ValueError("is_ai_tagged=True but no tools detected")
        if not self.is_ai_tagged and self.tools:
            raise ValueError("is_ai_tagged=False but tools present")


# Tool signature patterns
# These patterns match AI tool signatures in commit messages and trailers
# When adding new tools, update this catalog and bump catalog_version
TOOL_PATTERNS = {
    'claude-code': [
        re.compile(r'Co-Authored-By:\s*Claude\s*<noreply@anthropic\.com>', re.IGNORECASE),
        re.compile(r'anthropic\.com/claude', re.IGNORECASE),
        re.compile(r'Generated by Claude', re.IGNORECASE),
    ],
    'cursor': [
        re.compile(r'Co-Authored-By:\s*Cursor\s*AI\s*<.*?>', re.IGNORECASE),
        re.compile(r'cursor\.sh/commit', re.IGNORECASE),
        re.compile(r'Generated by Cursor', re.IGNORECASE),
    ],
    'copilot': [
        re.compile(r'Co-Authored-By:\s*GitHub\s*Copilot\s*<.*?>', re.IGNORECASE),
        re.compile(r'github\.com/features/copilot', re.IGNORECASE),
    ],
    'blackbox': [
        re.compile(r'Co-Authored-By:\s*Blackbox\s*AI\s*<.*?>', re.IGNORECASE),
    ],
    'cody': [
        re.compile(r'Co-Authored-By:\s*Sourcegraph\s*Cody\s*<.*?>', re.IGNORECASE),
        re.compile(r'sourcegraph\.com/cody', re.IGNORECASE),
    ],
    'codeium': [
        re.compile(r'Co-Authored-By:\s*Codeium\s*<.*?>', re.IGNORECASE),
    ],
    'codeium-bot': [
        re.compile(r'Co-Authored-By:\s*codeium-bot\s*<.*?>', re.IGNORECASE),
    ],
    'codestral': [
        re.compile(r'Co-Authored-By:\s*Codestral\s*<.*?>', re.IGNORECASE),
    ],
    'tabnine': [
        re.compile(r'Co-Authored-By:\s*Tabnine\s*<.*?>', re.IGNORECASE),
    ],
    'replit': [
        re.compile(r'Co-Authored-By:\s*Replit\s*Ghostwriter\s*<.*?>', re.IGNORECASE),
    ],
    'replit-bot': [
        re.compile(r'Co-Authored-By:\s*replit-bot\s*<.*?>', re.IGNORECASE),
    ],
    'sweep': [
        re.compile(r'Co-Authored-By:\s*Sweep\s*<.*?>', re.IGNORECASE),
    ],
    'windsurf': [
        re.compile(r'Co-Authored-By:\s*Windsurf\s*<.*?>', re.IGNORECASE),
    ],
    'netlify-coding': [
        re.compile(r'Co-Authored-By:\s*Netlify\s*AI\s*<.*?>', re.IGNORECASE),
    ],
}

# Catalog version — bump this when adding new tool signatures
CATALOG_VERSION = "2024-08-05"


def detect_tools(message: str) -> DetectionResult:
    """
    Detect AI tools from a commit message.

    This function runs all tool patterns against the commit message
    and returns all detected tools. A single commit may have multiple
    tools (e.g., both Claude and Cursor).

    Args:
        message: The commit message text (including trailers)

    Returns:
        DetectionResult containing detected tools and AI tag status

    Example:
        >>> msg = "feat: add function\\n\\nCo-Authored-By: Claude <noreply@anthropic.com>"
        >>> result = detect_tools(msg)
        >>> result.tools
        {'claude-code'}
        >>> result.is_ai_tagged
        True
    """
    if not message:
        return DetectionResult(tools=set(), is_ai_tagged=False, raw_message=message)

    detected_tools = set()

    for tool_name, patterns in TOOL_PATTERNS.items():
        for pattern in patterns:
            if pattern.search(message):
                detected_tools.add(tool_name)
                break  # No need to check other patterns for this tool

    return DetectionResult(
        tools=detected_tools,
        is_ai_tagged=bool(detected_tools),
        raw_message=message
    )


def detect_tools_from_fields(
    message: str,
    subject: Optional[str] = None
) -> DetectionResult:
    """
    Detect AI tools from commit message fields.

    This is a convenience wrapper that handles cases where message
    and subject are stored separately. It combines them before
    running detection.

    Args:
        message: The commit body (may be empty)
        subject: The commit subject line (may be empty)

    Returns:
        DetectionResult with detected tools
    """
    if subject:
        combined = f"{subject}\n\n{message}" if message else subject
    else:
        combined = message

    return detect_tools(combined)


def get_all_tool_names() -> Set[str]:
    """
    Get all tool names in the detection catalog.

    Returns:
        Set of all tool names that can be detected
    """
    return set(TOOL_PATTERNS.keys())


def get_catalog_version() -> str:
    """
    Get the current detection catalog version.

    Returns:
        Version string for the tool catalog
    """
    return CATALOG_VERSION


# ----------------------------------------------------------------------------
# Migration-path usage
# ----------------------------------------------------------------------------
# During corpus migration, this module is imported directly:
#
#     from shared.detection import detect_tools
#
#     for commit in commits:
#         result = detect_tools(commit['message'])
#         if result.is_ai_tagged:
#             for tool in result.tools:
#                 rollups.append((user, repo, tool, day, 1))
#
# No SQL reimplementation of these patterns — that would create two
# sources of truth that would drift.
# ----------------------------------------------------------------------------


if __name__ == "__main__":
    # CLI for testing detection
    import sys

    if len(sys.argv) < 2:
        print("Usage: python detection.py '<commit message>'")
        print("\nExample:")
        print('  python detection.py "feat: add feature\\n\\nCo-Authored-By: Claude <noreply@anthropic.com>"')
        sys.exit(1)

    test_message = sys.argv[1]
    result = detect_tools(test_message)

    print(f"Tools detected: {result.tools}")
    print(f"Is AI-tagged: {result.is_ai_tagged}")
    print(f"Catalog version: {CATALOG_VERSION}")
